# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjdhYjlmMjExZWM0ODVmMjZmMjk2ZDk1MDExZDc1MjYxMGNkYTM3ODE3NjY2NDg0Zjk4MGFmNmE0NTU2OGFmZjA3N2U2NzhkZmFmMDM1N2Q2M2ExZjRlZWRjNGNhZWJlMTMyMzQ2NDY0NzY5ZjRiMzA0MjdkOTkxNDhhNzBlY2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
